name: mnt_car_01
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.13
  - conda-forge::omegaconf=2.3.0
  - conda-forge::matplotlib==3.5.2
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pip:
    - pynput==1.7.6
    - opencv-python==4.7.0.72
    - pygame==2.5.0
    - gym==0.26.2